"""Initial Tables

Revision ID: e7547025d840
Revises: 0001
Create Date: 2026-10-05 20:01:44.963927
"""

import sqlalchemy as sa
from alembic import op

revision = "e7547025d840"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("building", sa.String(length=50), nullable=False),
        sa.Column("zone", sa.String(length=50), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "semesters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "time_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hour"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "student",
                "instructor",
                "coordinator",
                name="role",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("coordinator_id", sa.Integer(), nullable=True),
        sa.Column("min_course_load", sa.Integer(), nullable=False),
        sa.Column("max_course_load", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coordinator_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        op.f("ix_users_username"), "users", ["username"], unique=True
    )
    op.create_table(
        "calendar_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("calendar_id", sa.String(length=255), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("semester_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("enrollment", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["semester_id"], ["semesters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semester_id", "code"),
    )
    op.create_index(
        op.f("ix_courses_semester_id"), "courses", ["semester_id"], unique=False
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("semester_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                name="schedule_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("fitness", sa.Float(), nullable=False),
        sa.Column("generation_found", sa.Integer(), nullable=False),
        sa.Column("generations_run", sa.Integer(), nullable=False),
        sa.Column("report", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["semester_id"], ["semesters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schedules_semester_id"),
        "schedules",
        ["semester_id"],
        unique=False,
    )
    op.create_table(
        "course_instructors",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.Column(
            "preference",
            sa.Enum(
                "preferred",
                "qualified",
                name="course_preference",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"], ["courses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("course_id", "instructor_id"),
    )
    op.create_table(
        "course_pair_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_a_id", sa.Integer(), nullable=False),
        sa.Column("course_b_id", sa.Integer(), nullable=False),
        sa.Column(
            "rule_type",
            sa.Enum(
                "spread",
                "related",
                name="pair_rule_type",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "course_a_id <> course_b_id", name="different_courses"
        ),
        sa.ForeignKeyConstraint(
            ["course_a_id"], ["courses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["course_b_id"], ["courses.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_a_id", "course_b_id"),
    )
    op.create_table(
        "enrollments",
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"], ["courses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("student_id", "course_id"),
    )
    op.create_table(
        "schedule_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("time_slot_id", sa.Integer(), nullable=False),
        sa.Column("fitness", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"], ["schedules.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["time_slot_id"],
            ["time_slots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id", "course_id"),
    )
    op.create_index(
        op.f("ix_schedule_entries_schedule_id"),
        "schedule_entries",
        ["schedule_id"],
        unique=False,
    )
    op.create_table(
        "modification_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_entry_id", sa.Integer(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("assigned_to_id", sa.Integer(), nullable=True),
        sa.Column("proposed_room_id", sa.Integer(), nullable=True),
        sa.Column("proposed_time_slot_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "declined",
                name="request_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column("reviewer_comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["proposed_room_id"], ["rooms.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["proposed_time_slot_id"], ["time_slots.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["schedule_entry_id"], ["schedule_entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_modification_requests_assigned_to_id"),
        "modification_requests",
        ["assigned_to_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_modification_requests_schedule_entry_id"),
        "modification_requests",
        ["schedule_entry_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_modification_requests_schedule_entry_id"),
        table_name="modification_requests",
    )
    op.drop_index(
        op.f("ix_modification_requests_assigned_to_id"),
        table_name="modification_requests",
    )
    op.drop_table("modification_requests")
    op.drop_index(
        op.f("ix_schedule_entries_schedule_id"), table_name="schedule_entries"
    )
    op.drop_table("schedule_entries")
    op.drop_table("enrollments")
    op.drop_table("course_pair_rules")
    op.drop_table("course_instructors")
    op.drop_index(op.f("ix_schedules_semester_id"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_index(op.f("ix_courses_semester_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_table("calendar_links")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("time_slots")
    op.drop_table("semesters")
    op.drop_table("rooms")
    # ### end Alembic commands ###
